/*
 * Aithor :Thiracy Mary
 */

package com.capg.ftb.model;

import java.math.BigInteger;
import java.time.LocalDate;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name="Booking")
@ApiModel(value="Booking Entity")
public class Booking {
	
	@Id
	@GeneratedValue
	@ApiModelProperty(notes = "Autogenerated", required = true, position=1)
	private BigInteger bookingId;
	
	@OneToOne(targetEntity=Users.class,cascade=CascadeType.ALL)
	@JoinColumn(referencedColumnName="userId")
	@ApiModelProperty(notes = "Autogenerated", required = true, position=2)
	private Users userId;
	
	@Column
	@ApiModelProperty(notes = "Current date of Booking", required = false, position=3)
	private LocalDate bookingDate;
	
	@OneToMany(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
	@JoinColumn(name="bookedById") 
	@ApiModelProperty(notes = "List of Pasengers", required = false, position=4)
	private List<Passenger> passengerList;
	
	@Column
	@ApiModelProperty(notes = "Caluculated Automaticaly based on NoOfPasengers", required = false, position=5)
	private double ticketCost;
	
	@Column
	@ApiModelProperty(notes = "Scheduled Flight Id of Flight", required =true, position=6)
	private BigInteger scheduledFlightId;
	
	@Column
	@Min(value=1,message="atleast one passenger required")
	@ApiModelProperty(notes = "minimum 1 pasenger required", required = false, position=7)
	private int noOfPassangers;
	
	public BigInteger getBookingId() {
		return bookingId;
	}
	public void setBookingId(BigInteger bookingId) {
		this.bookingId = bookingId;
	}
	
	public Users getUserId() {
		return userId;
	}
	public void setUserId(Users userId) {
		this.userId = userId;
	}
	
	public LocalDate getBookingDate() {
		return bookingDate;
	}
	public void setBookingDate(LocalDate bookingDate) {
		this.bookingDate = bookingDate;
	}
	
	public List<Passenger> getPassengerList() {
		return passengerList;
	}
	public void setPassengerList(List<Passenger> passengerList) {
		this.passengerList = passengerList;
	}
	
	public double getTicketCost() {
		return ticketCost;
	}
	public void setTicketCost(double ticketCost) {
		this.ticketCost = ticketCost;
	}
	
	
	public Booking() {
		super();
	}
	public int getNoOfPassangers() {
		return noOfPassangers;
	}
	public void setNoOfPassangers(int noOfPassangers) {
		this.noOfPassangers = noOfPassangers;
	}
	
	public Booking(BigInteger bookingId,Users userId,LocalDate bookingDate,List <Passenger> passengerList,double ticketCost,BigInteger scheduledFlightId) {
		super();
		this.bookingId=bookingId;
		this.userId=userId;
		this.bookingDate=bookingDate;
		this.passengerList=passengerList;
		this.ticketCost=ticketCost;
		this.scheduledFlightId=scheduledFlightId;
	}
	public BigInteger getScheduledFlightId() {
		return scheduledFlightId;
	}
	public void setScheduledFlightId(BigInteger scheduledFlightId) {
		this.scheduledFlightId = scheduledFlightId;
	}
		
}

