package com.capg.ftb.model;

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.validation.annotation.Validated;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@Entity
@ApiModel
@Validated
public class Users {


	@Id
 	@GeneratedValue(generator = "IdGenerator")
	@ApiModelProperty(notes = "Autogenerated value", required = true, position=1)
	private BigInteger userId;
	
	@Column
	@ApiModelProperty(notes = "Type should be admin or customer", required = false, position=2)
	private String userType;
	
	@Column
	@ApiModelProperty(notes = "Unique user name required", required = false, position=3)
	private String userName;
	
	@Column
	@ApiModelProperty(notes = "Minimum length 8 characters", required = false, position=4)
	private String password;
	
	@Column
	@ApiModelProperty(notes = "Must be 11/12 digits", required = false, position=5)
	private String mobileNumber;
	
	@Column
	@ApiModelProperty(notes = "Strictly only valid emails are allowed", required = false, position=6)
	private String email;
	
	
	
	public Users() {
		super();
	}

	public Users(BigInteger userId, String userType, String userName, String password, String email,
			String mobileNumber) {
		super();
		this.userId = userId;
		this.userType = userType;
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.mobileNumber = mobileNumber;
	}

	public BigInteger getUserId() {
		return userId;
	}

	public void setUserId(BigInteger userId) {
		this.userId = userId;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	

}
